CREATE TABLE IF NOT EXISTS users (
    id SERIAL PRIMARY KEY,
    login VARCHAR(50) NOT NULL,
    password VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS itens_cardapio (
    id SERIAL PRIMARY KEY,
    item VARCHAR(100) NOT NULL,
    preco DECIMAL(10,2) NOT NULL
);